### ISSUE TITLE
Output Range for your model?

### ISSUE THREAD

**Issue by tejaschandramohan** [zwx8981/UNIQUE#16]
Hi, I am performing inference using your model for my dataset. For my dataset, the maximum score I get is 1.1834485530853271 and the minimum score is 0.5403027534484863. What is the output range for your model? Is it [0-1] or [1-5] or [1-10]?

**Comment by zwx8981** [comment]
@tejaschandramohan This model is trained via the pairwise learning-to-rank method, which eploits the relative ranking information of image pairs, instead of absolute MOS of images. Therefore, the output range is learned by the model itself and we didn't set any bound to it.

**Comment by tejaschandramohan** [comment]
In this case, does the output range depend on the MOS range of the dataset you trained or the output has no bounds altogether?

**Comment by zwx8981** [comment]
No bound. Empirically, it roughly lies in -3 to 3



发自我的iPhone


------------------ Original ------------------
From: tejaschandramohan ***@***.***&gt;
Date: Thu,Oct 7,2021 3:58 PM
To: zwx8981/UNIQUE ***@***.***&gt;
Cc: Onionbao ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [zwx8981/UNIQUE] Output Range for your model? (#16)





 
In this case, does the output range depend on the MOS range of the dataset you trained or the output has no bounds altogether?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tejaschandramohan** [comment]
Thank you. Also, could you run me through on how I proceed about re-training Unique for my dataset?

**Comment by zwx8981** [comment]
You don’t need to retrain unique, we have released the weights



发自我的iPhone


------------------ Original ------------------
From: tejaschandramohan ***@***.***&gt;
Date: Thu,Oct 7,2021 4:46 PM
To: zwx8981/UNIQUE ***@***.***&gt;
Cc: Onionbao ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [zwx8981/UNIQUE] Output Range for your model? (#16)





 
Thank you. Also, could you run me through on how I proceed about re-training Unique for my dataset?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tejaschandramohan** [comment]
I am looking to finetune this model by training it for my dataset only. 
In case of DBCNN (our conversation on the other repo), you mentioned to use dbcnn.py file to train it for my dataset. 
For unique, do I use scnn.py?

**Comment by zwx8981** [comment]
For UNIQUE, you should use Main.py instead. The key idea of UNIQUE is training a model on multiple datasets via the pairwise learning-to-rank method. So if you want to retrain the UNIQUE on your dataset, you shoudl first generate image pairs from your dataset. However, if you only train the UNIQUE on a single dataset, it makes less sense to train it using the learning-to-rank. You can directly train it using standard regression loss (MSE, MAE, etc.) While the backbone network of UNIQUE is ResNet-34, it is equivalent to finetune a ResNet-34 on your dataset.
